modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="eirode"
version="1.0.0"
displayName="eirode"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="trobi, MCreator"

[[dependencies.eirode]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




